# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: porerefiner.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import porerefiner_pb2


class PoreRefinerBase(abc.ABC):

    @abc.abstractmethod
    async def GetRuns(self, stream: 'grpclib.server.Stream[porerefiner_pb2.RunListRequest, porerefiner_pb2.RunList]') -> None:
        pass

    @abc.abstractmethod
    async def GetRunInfo(self, stream: 'grpclib.server.Stream[porerefiner_pb2.RunRequest, porerefiner_pb2.Run]') -> None:
        pass

    @abc.abstractmethod
    async def AttachSheetToRun(self, stream: 'grpclib.server.Stream[porerefiner_pb2.RunAttachRequest, porerefiner_pb2.RunAttachResponse]') -> None:
        pass

    @abc.abstractmethod
    async def RsyncRunTo(self, stream: 'grpclib.server.Stream[porerefiner_pb2.RunRsyncRequest, porerefiner_pb2.RunRsyncResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/porerefiner.rpc.PoreRefiner/GetRuns': grpclib.const.Handler(
                self.GetRuns,
                grpclib.const.Cardinality.UNARY_UNARY,
                porerefiner_pb2.RunListRequest,
                porerefiner_pb2.RunList,
            ),
            '/porerefiner.rpc.PoreRefiner/GetRunInfo': grpclib.const.Handler(
                self.GetRunInfo,
                grpclib.const.Cardinality.UNARY_UNARY,
                porerefiner_pb2.RunRequest,
                porerefiner_pb2.Run,
            ),
            '/porerefiner.rpc.PoreRefiner/AttachSheetToRun': grpclib.const.Handler(
                self.AttachSheetToRun,
                grpclib.const.Cardinality.UNARY_UNARY,
                porerefiner_pb2.RunAttachRequest,
                porerefiner_pb2.RunAttachResponse,
            ),
            '/porerefiner.rpc.PoreRefiner/RsyncRunTo': grpclib.const.Handler(
                self.RsyncRunTo,
                grpclib.const.Cardinality.UNARY_UNARY,
                porerefiner_pb2.RunRsyncRequest,
                porerefiner_pb2.RunRsyncResponse,
            ),
        }


class PoreRefinerStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetRuns = grpclib.client.UnaryUnaryMethod(
            channel,
            '/porerefiner.rpc.PoreRefiner/GetRuns',
            porerefiner_pb2.RunListRequest,
            porerefiner_pb2.RunList,
        )
        self.GetRunInfo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/porerefiner.rpc.PoreRefiner/GetRunInfo',
            porerefiner_pb2.RunRequest,
            porerefiner_pb2.Run,
        )
        self.AttachSheetToRun = grpclib.client.UnaryUnaryMethod(
            channel,
            '/porerefiner.rpc.PoreRefiner/AttachSheetToRun',
            porerefiner_pb2.RunAttachRequest,
            porerefiner_pb2.RunAttachResponse,
        )
        self.RsyncRunTo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/porerefiner.rpc.PoreRefiner/RsyncRunTo',
            porerefiner_pb2.RunRsyncRequest,
            porerefiner_pb2.RunRsyncResponse,
        )
